from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="End-to-end entrypoint: P&ID image -> VLM router-input JSON -> router-layer -> generation JSON."
    )
    parser.add_argument(
        "--image",
        default="VLM-layer/examples/TestPID.png",
        help="Path to input P&ID image.",
    )
    parser.add_argument(
        "--router-input-out",
        default="VLM-layer/output/router_input_from_vlm.json",
        help="Output path for router-layer input JSON generated by VLM.",
    )
    parser.add_argument(
        "--generation-out",
        default="router-layer/output/router_output_from_vlm.json",
        help="Output path for generation-layer JSON produced by router-layer.",
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Optional model override (otherwise uses global_config.json openrouter.chat_model).",
    )
    parser.add_argument(
        "--no-schema-validate",
        action="store_true",
        help="Skip JSON schema validation for router input and generation output.",
    )
    return parser.parse_args()


def _bootstrap_vlm_package(repo_root: Path) -> None:
    vlm_pkg_root = repo_root / "VLM-layer"
    if str(vlm_pkg_root) not in sys.path:
        sys.path.insert(0, str(vlm_pkg_root))


def main() -> None:
    args = _parse_args()
    repo_root = Path(__file__).resolve().parent
    _bootstrap_vlm_package(repo_root)

    from vlm_layer.pipeline import PipelineIO, run_end_to_end

    io = PipelineIO(
        image_path=(repo_root / args.image).resolve(),
        prompts_path=(repo_root / "VLM-layer/config/prompts.json").resolve(),
        global_config_path=(repo_root / "global_config.json").resolve(),
        router_schema_path=(repo_root / "router-layer/router-input-protocol/schema/router_input_v1.json").resolve(),
        generation_schema_path=(repo_root / "chemical-piping-lib/chemical_piping_lib/schema/protocol_v1.json").resolve(),
        router_input_output_path=(repo_root / args.router_input_out).resolve(),
        generation_output_path=(repo_root / args.generation_out).resolve(),
        model_override=args.model,
    )

    if not io.image_path.is_file():
        raise FileNotFoundError(f"Input image not found: {io.image_path}")

    result = run_end_to_end(
        repo_root=repo_root,
        io=io,
        validate_schema=not args.no_schema_validate,
    )

    print("=" * 72)
    print("Pipeline completed")
    print(f"Image:               {io.image_path}")
    print(f"Router input JSON:   {io.router_input_output_path}")
    print(f"Generation JSON:     {io.generation_output_path}")
    print(f"Nodes / Lines:       {len(result.router_input.get('nodes', []))} / {len(result.router_input.get('lines', []))}")
    print("=" * 72)


if __name__ == "__main__":
    main()

